In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
#numpy as np(alias alternative nameing)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr = np.array((1, 2, 3, 4, 5))# set in terms of tuple it changed to array of list 

print(arr)
print(type(arr))#get the type of object

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
#dimenstions in array
import numpy as np

#0-D or scalar arrays
arr= np.array((45))
print(arr)

#1-D arrays
arr_1=np.array([7,8,9,10])
print("1-D arrays:",arr_1)

#cretaing 2-D arrays
arr_2= np.array([[1,2,3],[4,5,6]])
print("2-D arrays:",arr_2)

#cretaing 3-D arrays
arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3-D arrays:",arr_3)

#creating 4-D arrays
arr_4 = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])
print("4-D arrays:", arr_4)

#finding the number of dimenstions  an array

print(arr.ndim)
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)
print(arr_4.ndim)

#defining the number dimestions using ndmin
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print("number of dimenstions:",arr.ndim)

45
1-D arrays: [ 7  8  9 10]
2-D arrays: [[1 2 3]
 [4 5 6]]
3-D arrays: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
4-D arrays: [[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
0
1
2
3
4
number of dimenstions: 5


In [3]:
#Numpy array indexing
import numpy as np 

arr= np.array([1,2,3,4,5])
print(arr[0]) # accessing array element using index
print(arr[1] + arr[2])# adding the accesing element

#accessing a 2-D arrays
arr_2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr_2)
print('2nd element on 1st row: ', arr_2[0, 1])
print('last element on 2nd row:',arr_2[1,-1])

#accessing a 3-D arrays
arr_3 =  np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3)
print(arr_3[0,1,2]) #array[layer][row][column]


1
5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
last element on 2nd row: 10
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [4]:
#NumPy Array Slicing

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])#1-D slicing

#2-D array slicing
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2, 1:3])

#3-D array slicing
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
"""
: → all layers
: → all rows
1: → columns from index 1 onward
"""
print(arr[:, :, 1:])

#negative index slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[::-1])#reversing the array

[2 3 4 5]
[[2 3]
 [5 6]]
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
[5 4 3 2 1]


In [5]:
#Numpy Data types
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

#creating an array with defined data type
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


int64
<U6
[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#NumPy Array Copy vs View
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
#x = arr.copy()
x = arr.view()
arr[0] = 42# changing an element 

print(arr)
print(x)

In [12]:
#NumPy Array Shape
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
#arr=np.array([1,2,3,4,5],ndmin=5)
#print(arr)
#print('shape of array :', arr.shape)

rows, cols = arr.shape
print(rows)
print(cols)

#NumPy Array Reshaping
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr= arr.reshape(4,3)#1-D to 2-D
newarr= arr.reshape(2,2,3)#1-D to 3-D
print(new_arr)
print(newarr)


(2, 4)
2
4
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
